language: r
sudo: required

warnings_are_errors: false

r_github_packages:
  - hadley/assertthat
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
