language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

r_github_packages:
  - mattflor/chorddiag
  - hadley/assertthat
  - hadley/testthat
  - wch/webshot
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
