language: r
sudo: false
cache: packages

warnings_are_errors: true

r_github_packages:
  - hadley/assertthat
  - hadley/testthat
  - wch/webshot
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
