language: c
services: PostgreSQL

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - mkdir ~/.R
  - ./travis-tool.sh install_deps

before_script:
  - R CMD INSTALL .

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

branches:
  except:
  - /^devel-/

notifications:
  email:
    on_success: change
    on_failure: change
