---
title: "unisis/dwh/table"
author: "Alain Clément-Pavon"
date: "2015-01-21"
output: html_document
---

# Initialization

```{r}
library(modulr)
```

# Definition

```{r}
"unisis/dwh/table" %requires% list("unisis/dwh/query") %provides% (
  table_factory <- function(query) {
    get_all <- function() {
      query("SELECT owner, table_name FROM all_tables")
    }

    get <- function(table_name) {
      query(sprintf("SELECT * from DWH.%s", table_name))
    }

    list(
        get_all = get_all
      , get = get
      )
  })
```
# Tests

```{r}
library(testthat)
library(RUnit)

"unisis/dwh/query.mock" %provides%
  function() {
    function(sql_query_string) {
      if(sql_query_string == "SELECT owner, table_name FROM all_tables")
        return(data.frame(owner="a", table_name="b"))
      data.frame(c1="a", c2="b")
      }
    }

"unisis/dwh/table.mock" %requires% 
  list("unisis/dwh/query.mock") %provides%
  table_factory

"unisis/dwh/table.test" %requires%
  list("unisis/dwh/table.mock") %provides%
  function(table) {
    context("unisis/dwh/table")
    test_that("all tables are correctly queried", {
      expect_that(table$get_all(), 
        equals(data.frame(owner="a", table_name="b")))
      expect_that(table$get(""), 
        equals(data.frame(c1="a", c2="b")))
      })
    }

#instanciate("unisis/dwh/table.test")

#test.table <- "unisis/dwh/table.test" %requires%
#  list("unisis/dwh/table.mock") %provides%
#  function(table) {
#    checkEquals(table$get_all(), data.frame(owner="a", table_name="b"))
#    checkEquals(table$get(""), data.frame(c1="a", c2="c"))
#    }
```

