---
title: "unisis/dwh"
author: "Alain Clément-Pavon"
date: "2015-01-21"
output: html_document
---

# Initialization

```{r initialization}
library(modulr)
```

# Modules

## unisis/dwh/connection

### Default options

```{r}
"unisis/dwh/connection" %has_default_option% list(
  configs = list(
    dev = list(
      host = "devcog.unil.ch",
      port = 1521,
      service_name = "Sinfpildev.unil.ch",
      username = "unisis",
      password = "unisis35"
    ),
    prod = list(
      host = "prdcog.unil.ch",
      port = 1521,
      service_name = "Sinfpilprd.unil.ch",
      username = "unisis",
      password = "unisis35"
    )
  ),
  stage = "prod"
)
```

### Definition

```{r}
"unisis/dwh/connection" %requires% list("modulr") %provides% 
  function(modulr) {
    library(DBI, ROracle)
    get <- function() {
      options <- modulr$get_module_options()

      driver <- dbDriver("Oracle")

      host <- options$configs[[options$stage]]$host
      port <- options$configs[[options$stage]]$port
      service_name <- options$configs[[options$stage]]$service_name

      connect_string <- paste(
        "(DESCRIPTION=",
        "(ADDRESS=(PROTOCOL=tcp)(HOST=", host, ")(PORT=", port, "))",
        "(CONNECT_DATA=(SERVICE_NAME=", service_name, ")))", sep = "")

      dbConnect(
        driver,
        username = options$configs[[options$stage]]$username,
        password = options$configs[[options$stage]]$password,
        dbname = connect_string)
      }
    list(
      get = get,
      disconnect = disconnect
      )
    }
```

## unisis/dwh/query

### Definition

```{r}
"unisis/dwh/query" %requires% list("unisis/dwh/connection") %provides%
  function(connection) {
    library(DBI)
    function(sql_query_string)
    connection_handler <- connection$get()
    cursor <- dbSendQuery(
      connection_handler,
      sql_query_string
      )
    query <- fetch(cursor)
    connection$disconnect(connection_handler)
    query
    }
```

## unisis/dwh/table

### Definition

```{r}
"unisis/dwh/table" %requires% list("unisis/dwh/query") %provides%
  function(query) {
    get_all <- function() {
      query("SELECT owner, table_name FROM all_tables")
    }

    get <- function(table_name) {
      query(sprintf("SELECT * from DWH.%s", table_name))
    }

    list(
        get_all = get_all
      , get = get
      )
  }
```

## unisis/dwh/raw/table

### Definition

```{r}
"unisis/dwh/raw/table" %requires% list("unisis/dwh/table") %provides%
  function(table) {
    get_all <- function() {
      subset(table$get_all(), grepl("^RAW", TABLE_NAME))
      }  
    get <- function(raw_table_name) {
      table$get(paste0("RAW", raw_table_name))
      }
    list(
      get_all = get_all,
      get = get
      )
    }
```

# Tests

## Mockups

```{r}
#"unisis/dwh/get_connection" %provides%
#  function() {
#    function() {}
#    }
```

